# Generated by Django 5.1.1 on 2025-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
