# Generated by Django 5.1.1 on 2024-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="players",
            field=models.JSONField(default=list),
        ),
    ]
