# Generated by Django 5.1.1 on 2024-12-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="max_players",
        ),
        migrations.AddField(
            model_name="tournament",
            name="matches",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLAYING", "Playing"),
                    ("PENDING", "Pending"),
                    ("FINISHED", "Finished"),
                    ("READY", "Ready"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
