# Generated by Django 5.1.1 on 2024-12-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_tournament_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="players",
            field=models.JSONField(default=list),
        ),
    ]
