# Generated by Django 5.1.1 on 2024-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totd',
            field=models.CharField(null=True),
        ),
    ]
