# Generated by Django 5.1.1 on 2024-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
