# Generated by Django 5.1.1 on 2024-12-05 17:03

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_totd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="totd",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_2FA",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="qrcode_path",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp",
            field=models.CharField(default=pyotp.random_base32),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="winrate",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
