# Generated by Django 5.1.1 on 2024-10-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='user',
            name='tournament',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='db.tournament'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to='db.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Pending Activation')], default=1, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Match_History',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
